// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VShop.DAL.Models.Db;

public partial class Comment
{
    public int Id { get; set; }

    public string Content { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? ParentId { get; set; }

    public Guid UserId { get; set; }

    public int ProductId { get; set; }

    public virtual Product Product { get; set; }

    public virtual User User { get; set; }
}