// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VShop.DAL.Models.Db;

public partial class District
{
    public int Id { get; set; }

    public string Name { get; set; }

    public int ProvinceId { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Province Province { get; set; }

    public virtual ICollection<Ward> Wards { get; set; } = new List<Ward>();
}