// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VShop.DAL.Models.Db;

public partial class Order
{
    public int Id { get; set; }

    public string FullName { get; set; }

    public string Email { get; set; }

    public string PhoneNumber { get; set; }

    public string Address { get; set; }

    public string Note { get; set; }

    public DateTime OrderDate { get; set; }

    public int Status { get; set; }

    public Guid? UserId { get; set; }

    public string District { get; set; }

    public string Province { get; set; }

    public string Ward { get; set; }

    public int? VoucherId { get; set; }

    public double DeliveryFee { get; set; }

    public int TypePayment { get; set; }

    public virtual ICollection<OrderDetail> OrderDetails { get; set; } = new List<OrderDetail>();

    public virtual User User { get; set; }

    public virtual Voucher Voucher { get; set; }
}