// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VShop.DAL.Models.Db;


public partial class Post
{
    public int Id { get; set; }

    public string Title { get; set; }

    public string Image { get; set; }

    public string Content { get; set; }

    public bool Status { get; set; }
}