// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace VShop.DAL.Models.Db;


public partial class Voucher
{
    public int Id { get; set; }

    public string DiscountCode { get; set; }

    public double DiscountValue { get; set; }

    public double MinimumValue { get; set; }

    public int Quantity { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public string Describe { get; set; }

    public bool Status { get; set; }

    public DateTime CreatedDate { get; set; }

    public string CreatedBy { get; set; }

    public bool DiscountAmount { get; set; }

    public bool DiscountPercentage { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}